---
title: "Clase 8: Modelos jerárquicos de supervivencia"
author: "David Murillo"
format:
  html:
    css: styles.css
---

El tema de esta clase es el célebre modelo Cormack-Jolly-Seber, o CJS (Cormack, 1964; Jolly, 1965; Seber, 1965), uno de los modelos estadísticos más famosos en ecología. El modelo CJS requiere datos de captura-recaptura en vivo (también llamados marcaje-recaptura o marcaje-reseñamiento) de individuos reconocibles individualmente. Esto generalmente significa individuos marcados (etiquetados), pero la identificación genética y, a veces, la variabilidad natural en el color o los patrones de plumas/pelaje/piel pueden servir igualmente bien para identificar de manera única a los individuos. El modelo CJS produce estimaciones de la probabilidad aparente de supervivencia  $\phi$, la probabilidad de que un individuo marcado permanezca vivo y en el área de estudio entre dos puntos temporales en los que se realizan los reconocimientos, y de la probabilidad de recaptura *p*, la probabilidad de que un individuo marcado se encuentre en un punto temporal determinado (nótese que la identificación en el tiempo amplio se refiere al re-avistamiento y cualquier otra forma de identificación individual). Sorprendentemente, el modelo CJS también estima la probabilidad de un evento (muerte), ¡aunque nunca observamos directamente ese evento!

Las bases y el diseño para producir datos susceptibles de análisis bajo un modelo CJS es aquel en el que se define un área de estudio fija y luego se sale y se intenta capturar y marcar tantos individuos como se definan. En ocasiones fijas, el primer registro de un individuo reconocible por sus marcas naturales o genéticas, etc. es funcionalmente idéntico al primer marcado de ese individuo. Luego, en cada ocasión, se registra la identidad de los individuos que ya tienen una marca y se coloca una nueva marca en aquellos que no la tienen. Los datos básicos se resumen en la matriz de historial de captura o detección **Y** de dimensiones *n* x *T*, donde *T* es el número de ocasiones Y *n* es el número de animales marcados primero hasta la ocasión *T*-1; aquellos marcados en la ocasión *T* no proporcionan ninguna información sobre la supervivencia y pueden ignorarse. La entrada (*i*,*t*) de la matriz contiene un 1 cuando el individuo *i* fue detectado en la ocasión 1 y un 0 cuando no lo fue.

Es crucial que la extensión espacial de un área de estudio permanezca igual a lo largo del tiempo, porque en el modelo CJS estamos estimando la supervivencia aparente: el producto de la supervivencia real (*S*) y la probabilidad de permanecer en el área de estudio (es decir, fidelidad *F*). A partir de datos simples (no espaciales) de captura-recaptura, no es posible separar estos dos componentes (aunque se hace posible con modelos CJS espacialmente explícitos. Por lo tanto, si extiende su área de estudio a lo largo del tiempo, más individuos marcados tenderán a permanecer dentro de sus límites, *F* aumentará y también lo hará la supervivencia aparente. A menudo, las ocasiones de captura se espacian regularmente, por ejemplo, durante la temporada de reproducción en cada año, pero no es necesario que así sea, y hay diferentes formas de lidiar con intervalos de tiempo desiguales. Además, lo ideal es que la captura sea instantánea y no que se extienda de forma continua en el tiempo (también existen modelos de supervivencia para datos recopilados en tiempo continuo. Por último, si queremos que nuestras estimaciones caractericen a la población en general en lugar de solo a la muestra de individuos capturados, debemos apuntar a capturar una muestra aleatoria de individuos de la población (y sin extendernos en esto, solo afirmamos que esto puede ser más desafiante de lo que parece a primera vista).

## Modelos básicos de Cormack-Jolly-Seber

### El modelo básico de CJS como modelo de espacio de estados o jerárquico

Fundamentalmente, el modelo CJS puede considerarse un modelo jerárquico o de espacio de estados (SSM), porque distingue entre un estado latente binario (vivo, muerto) y un estado observado binario (detectado, no detectado). La dinámica del estado latente se describe de la manera habitual de un SSM, describiendo el estado inicial de cada individuo y utilizando una regla probabilística por la que cambia de estado desde el momento *t* a *t* +1. Sin embargo, hay dos cosas un tanto peculiares. En primer lugar, el estado latente inicial de cada individuo no se modela de forma probabilística, sino que se fija en 1. Es decir, el modelo condiciona la primera captura (cuando el individuo estaba vivo por definición) y solo describe los eventos aleatorios posteriores a la primera captura. Esto es bastante diferente en otros modelos de estado sólido relacionados para respuestas binarias, como el modelo Jolly-Seber o en el modelo de ocupación dinámica, los cuales modelan una matriz de historial de detección desde el inicio (es decir, con la columna 1) de manera probabilística. En segundo lugar, en el modelo CJS, las transiciones en el estado latente solo son posibles en una dirección, de vivo a muerto. Esto es nuevamente diferente en el modelo de ocupación dinámica relacionado, donde las colonizaciones son posibles. Por último, los modelos típicos de "supervivencia del nido" o "destino conocido" difieren del modelo CJS principalmente por la ausencia de un modelo de observación, porque su estado latente se observa perfectamente si es que se observa. Todos estos modelos son equivalentes a los modelos ocultos de Markov (HMM; Zucchini et al., 2016): modelos de series temporales jerárquicos con estados discretos solamente y donde la regla de transición se refiere a un solo paso atrás en el tiempo, es decir, el modelo es markoviano de orden 1. Sin embargo, de manera un tanto confusa, la probabilidad del modelo CJS a menudo se expresa de una manera no jerárquica, en lugar de construirse de una manera jerárquica explícita. Para esto, la matriz básica del historial de captura se agrega por cohorte de liberación y ocasión de recaptura en el llamado *formato m-array*. La probabilidad de cada celda de esta matriz agregada se puede expresar como una función de parámetros específicos del tiempo de aparente supervivencia y recaptura, y el ajuste del modelo se realiza maximizando una probabilidad multinomial producto. Esta es la probabilidad maximizada en la mayoría de los programas frecuentistas para el modelo CJS.

Con el formato m-array, la probabilidad CJS se colapsa sobre los estados latentes *z* (ver más abajo) y, por lo tanto, en un sentido técnico, el modelo ya no es jerárquico, aunque conceptualmente lo es. En cambio, en programas bayesianos como BUGS, podemos ajustar el modelo tanto utilizando la construcción jerárquica directa de la probabilidad, como utilizando la agregación de matriz m-array. Podría decirse que la primera es conceptualmente más fácil de entender y, además, permite ajustar modelos más generales, pero la segunda es computacionalmente más eficiente (y a menudo mucho más eficiente).

En el formato SSM, los datos de historial de captura observados y, son iguales a 1 si el individuo *i* es detectado (es decir, capturado) en la ocasión *t* y 0 si no es detectado. Se describen en términos de una variable latente $z_{i,t}$, que dice si ese individuo estaba vivo ($z_{i,t} = 1$) o muerto ($z_{i,t} = 0$) en la ocasión *t*, y dos parámetros, las probabilidades de supervivencia aparente $\phi$ y de recaptura $p$, que, para mayor claridad, aquí asumimos primero que son constantes. Dado que el modelo CJS se define condicional a la primera captura y se conoce el estado verdadero en la primera captura, también necesitamos un vector que contenga la ocasión de marcado, llamado $f$, para describir los datos observados de manera probabilística, es decir, para formar su probabilidad. Luego, describimos la parte latente del sistema en dos líneas:

$z_{i,f = 1}$ (para la ocasión de marcado)

$z_{i,t+1}|z_{i,t} \sim Bernoulli(z_{i,1}\phi)$ (para todas las ocasiones posteriores)

Por lo tanto, después de la ocasión de marcado, el estado vivo/muerto es un simple ensayo de Bernoulli condicional con probabilidad de éxito $z_i\phi$; la multiplicación con $z_i$, asegura que el individuo $i$ permanezca muerto una vez que haya muerto. Este es el submodelo de proceso del modelo jerárquico. Para describir el proceso de observación, asumimos que no hay falsos positivos (por ejemplo, ninguna marca se identifica erróneamente) y adoptamos otra distribución de Bernoulli (condicional).

$y_{i,t}|z_{i,t}\sim Bernoulli(z_{i,t}p)$ El (sub)modelo de observación

Por lo tanto, que un individuo sea detectado o no depende de dos cosas: si está vivo y de la probabilidad de recaptura $p$. En el caso más general, podemos permitir que ambos parámetros del modelo difieran según el individuo $i$ y el tiempo $t$ y, a continuación, se puede especificar una gran cantidad de patrones para ellos agregando efectos de covariables o efectos aleatorios. Un conjunto de presencia o ausencia de efectos temporales conduce a la clasificación clásica de modelos $\phi(t)p(t)$, $\phi(t)p(.)$, $\phi(.)p(t)$, $\phi(.)p(.)$ clasificación de modelos con parámetros que son constantes (.) o totalmente dependientes del tiempo ($t$) (Cooch y White, 2019).

Referencia, Capítulo 3: [Aplied Hierarchical Modeling in Ecology, Volumen 2](https://www.sciencedirect.com/book/9780128237687/applied-hierarchical-modeling-in-ecology-analysis-of-distribution-abundance-and-species-richness-in-r-and-bugs)

::: panel-tabset

## Datos sobre el mosquitero musical británico *Phylloscopus trochilus*



:::

