---
title: "Clase 7: Modelado de interacciones entre especies (ocupación)"
author: "David Murillo"
format:
  html:
    css: styles.css
---


Este capítulo trata sobre el modelado de interacciones entre dos o más especies en términos de patrones observados en la ocurrencia. Las interacciones entre especies son fundamentales para la ecología, ya que pueden ser resultado de mecanismos ecológicos tan importantes como la competencia, la depredación y el mutualismo, denominados colectivamente interacciones bióticas. En sentido estricto, solo los experimentos manipulativos o las observaciones conductuales directas de individuos permiten decidir si una asociación estadística observada puede atribuirse a interacciones bióticas reales, efectos ambientales o ambos mecanismos juntos. Por ejemplo, una correlación espacial negativa en la ocurrencia o abundancia de dos especies puede deberse a una interacción antagónica, como la competencia, el parasitismo o la depredación. Alternativamente, puede ser simplemente el resultado de diferentes preferencias de hábitat de las dos especies, es decir, filtrado de hábitat. O puede ser el resultado de una combinación de ambos mecanismos. Esta es quizás la advertencia principal para la mayoría de las aplicaciones de los modelos de este capítulo: que una correlación no implica necesariamente causalidad.

Cuando decimos "interacciones entre especies" en esta clase, nos referimos a una asociación o no independencia en los parámetros de múltiples especies en un modelo de ocurrencia. Es decir, utilizamos el término "interacción" en un sentido puramente descriptivo, estadístico o correlativo. Cubriremos modelos multiespecie para ocurrencia, que tienen parámetros específicos para dar cuenta de la posible no independencia entre pares de especies. Además, estos modelos nos permitirán, en diferentes grados, probar hipótesis sobre posibles mecanismos biológicos subyacentes a dicha no independencia entre múltiples especies. Algunos de estos modelos tienen un toque claramente mecanicista, pero ni siquiera ellos nos permitirán hacer inferencias sólidas sobre interacciones reales entre individuos de múltiples especies, a menos que tengamos el tipo correcto de datos (observaciones experimentales o de comportamiento). Sin embargo, los modelos de esta clase pueden ser herramientas poderosas para descubrir patrones: pueden señalar algunos pares de especies como candidatos para interacciones bióticas directas. El descubrimiento de fuertes asociaciones positivas o negativas en la abundancia o la ocurrencia (o posiblemente en otro parámetro) puede ser seguido por investigaciones más enfocadas en los posibles fundamentos mecanicistas de tales patrones. Además, si ajustamos estos modelos a los datos recopilados en el contexto de un experimento manipulativo diseñado para aislar algún mecanismo biológico, entonces nos permitirán hacer inferencias sólidas sobre los efectos de estos mecanismos. Y como siempre, si nuestros modelos muestran una asociación positiva o negativa que fue predicha en base a un conocimiento a priori sobre posibles interacciones bióticas entre estas especies, entonces esto proporciona una inferencia más sólida sobre la existencia de estas interacciones. 

Referencia: [Aplied Hierarchical Modeling in Ecology, Volumen 2](https://www.sciencedirect.com/book/9780128237687/applied-hierarchical-modeling-in-ecology-analysis-of-distribution-abundance-and-species-richness-in-r-and-bugs)

